# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0004_auto_20180927_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_url',
        ),
    ]
